name: checkmate_prod

services:
  checkmate_nginx:
    container_name: checkmate_nginx
    image: nginx:1.29-alpine
    ports:
      - "75:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - checkmate_node
    networks:
      - checkmate_network

  checkmate_node:
    container_name: checkmate_node
    build: .
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /app/node_modules
      - ./public:/app/public
    ports:
      - "3001:3000"
    depends_on:
      - checkmate_db
    networks:
      - checkmate_network

  checkmate_db:
    image: postgres:15
    container_name: checkmate_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - checkmate_network
    volumes:
      - ./pgdata-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  checkmate_network:
    external: true
    name: checkmate_network